### ISSUE TITLE
No output with .grab

### ISSUE THREAD

**Issue by Sohrab82** [ComputerNerd/simpleFrameGrabber#5]
Hi,

I set up everything and run the qqvga, but it opens a window which is always black, no picture!
Any idea?

When I build the code, I get these warnings, is it normal?!

main.c: In function ‘getJpeg’:
main.c:220:9: warning: format ‘%u’ expects argument of type ‘unsigned int’, but argument 2 has type ‘size_t {aka long unsigned int}’ [-Wformat=]
  printf("Size: %u\n",sz);
         ^
main.c: In function ‘main’:
main.c:342:11: warning: format ‘%u’ expects argument of type ‘unsigned int’, but argument 2 has type ‘size_t {aka long unsigned int}’ [-Wformat=]
    printf("Jpeg grabbed size: %u\n",sz);
           ^
main.c:372:4: warning: passing argument 1 of ‘jpeg_CreateCompress’ from incompatible pointer type [-Wincompatible-pointer-types]
    jpeg_create_compress(&cinfo);
    ^
In file included from main.c:27:0:
/usr/include/jpeglib.h:904:14: note: expected ‘j_compress_ptr {aka struct jpeg_compress_struct *}’ but argument is of type ‘struct jpeg_decompress_struct *’
 EXTERN(void) jpeg_CreateCompress (j_compress_ptr cinfo, int version,
              ^
main.c:418:13: warning: unused variable ‘row_pointer’ [-Wunused-variable]
    JSAMPROW row_pointer[1];
             ^
main.c:474:7: warning: enumeration value ‘JPEG’ not handled in switch [-Wswitch]
       switch(colspace){
       ^
main.c:495:6: warning: enumeration value ‘JPEG’ not handled in switch [-Wswitch]
      switch(colspace){

Thanks

**Comment by akshulg** [comment]
I am having the same problem. Black screen. Did you get the solution?

**Comment by Sohrab82** [comment]
It was not the code, the warnings are not important either.
It had something to do with the wiring and also one of my Arduino IO pins.
I have also tried the windows java code, actually that one is Much faster than this one!!
